# extra configuration used by constellation

repos:
  - kubernetes
  - fedora
  - fedora-modular
  - fedora-updates-modular

repo-packages:
  - repo: kubernetes
    packages:
      - kubelet
      - kubeadm
      - kubectl
  - repo: fedora
    packages:
      - conntrack-tools
  - repo: fedora-coreos-pool
    packages:
      - veritysetup

packages:
  - tpm2-tools
  - vim-common # provides xxd (needed for GCP nvme disk naming)

postprocess:
  # empty /etc/cni/net.d as crio rpm has bad default config there
  - |
    #!/usr/bin/env bash
    set -xeuo pipefail
    rm -rf /etc/cni/net.d/*
