# extra configuration used by constellation

repos:
  - crio
  - kubernetes
  - fedora
  - fedora-modular
  - fedora-updates-modular

repo-packages:
  - repo: crio
    packages:
      - crio
  - repo: kubernetes
    packages:
      - kubelet
      - kubeadm
      - kubectl
  - repo: fedora
    packages:
      - conntrack-tools
  - repo: fedora-coreos-pool
    packages:
      - veritysetup

packages:
  - tpm2-tools

postprocess:
  # empty /etc/cni/net.d as crio rpm has bad default config there
  - |
    #!/usr/bin/env bash
    set -xeuo pipefail
    rm -rf /etc/cni/net.d/*
